CREATE DATABASE pmweb;
GO

USE pmweb; 
GO

CREATE TABLE CLIENTES (
    ID INT PRIMARY KEY,
    EMAIL VARCHAR(255),
    NOME VARCHAR(255),
    DATA_NASCIMENTO DATE,
    CIDADE VARCHAR(100),
    UF CHAR(2),
    PERMISSAO_RECEBE_EMAIL BIT
);
GO

CREATE TABLE PEDIDOS (
    ID_CLIENTE INT,
    ID_PEDIDO INT,
    ID_PRODUTO INT,
    DEPARTAMENTO VARCHAR(100),
    QUANTIDADE INT,
    VALOR_UNITARIO DECIMAL(10, 2),
    PARCELAS INT,
    DATA_PEDIDO DATE,
    MEIO_PAGAMENTO VARCHAR(50),
    STATUS_PAGAMENTO VARCHAR(50)
);
GO

CREATE TABLE LOG_RODADA (
    ID_LOG INT IDENTITY(1,1) PRIMARY KEY,
    DATA_INICIO DATETIME,
    DATA_FIM DATETIME,
    QTD_CLIENTES_PROCESSADOS INT,
    QTD_PEDIDOS_PROCESSADOS INT,
    STATUS_RODADA VARCHAR(50),
    MENSAGEM VARCHAR(MAX)
);
GO

CREATE TABLE STG_CLIENTES (
    ID VARCHAR(50),
    EMAIL VARCHAR(255),
    NOME VARCHAR(255),
    DT_NASC VARCHAR(50),
    SEXO VARCHAR(50),
    CADASTRO VARCHAR(50),
    CIDADE VARCHAR(100),
    ESTADO VARCHAR(50),
    RECEBE_EMAIL VARCHAR(50),
    COL1 VARCHAR(50), COL2 VARCHAR(50), COL3 VARCHAR(50), COL4 VARCHAR(50)
);
GO

CREATE TABLE STG_PEDIDOS (
    COD_CLIENTE VARCHAR(50),
    COD_PEDIDO VARCHAR(50),
    CODIGO_PRODUTO VARCHAR(50),
    DEPTO VARCHAR(100),
    QUANTIDADE VARCHAR(50),
    VALOR_UNITARIO VARCHAR(50),
    QTD_PARCELAS VARCHAR(50),
    DT_PEDIDO VARCHAR(50),
    MEIO_PAGTO VARCHAR(50),
    STATUS_PAGAMENTO VARCHAR(50)
);
GO