BULK INSERT STG_CLIENTES
FROM 'C:\Integracao\CADASTROS.csv'
WITH (FIELDTERMINATOR = ';', ROWTERMINATOR = '\n', FIRSTROW = 2, CODEPAGE = 'ACP');
GO

BULK INSERT STG_PEDIDOS
FROM 'C:\Integracao\PEDIDOS.csv'
WITH (FIELDTERMINATOR = ';', ROWTERMINATOR = '\n', FIRSTROW = 2, CODEPAGE = 'ACP');
GO